using TranscriptionOverlay.Models;

namespace TranscriptionOverlay.Services;

public sealed class TranscriptionModelCatalog
{
    public const string DefaultModelKey = "voxtral-mini-3b";

    private static readonly IReadOnlyList<TranscriptionModelDefinition> Definitions =
    [
        new(
            Key: "phonon-2",
            DisplayName: "Phonon-2",
            RepoId: "FermionResearch/Phonon-2",
            SizeLabel: "164 MB",
            DownloadPatterns:
            [
                "config.json",
                "packed_manifest.json",
                "phonon-2.bps.tar.zst",
                "SHA256SUMS.txt",
                "README.md",
                "NOTICE",
                "LICENSE-CODE-Apache-2.0.txt",
                "LICENSE-WEIGHTS-CC-BY-4.0.txt",
            ],
            RuntimeKind: ModelRuntimeKind.Phonon,
            SupportsFileTranscription: true,
            SupportsRealtimeTranscription: false,
            SupportsWindowsRuntime: true,
            SupportsLinuxRuntime: true,
            SupportsMacOsRuntime: true,
            RequiresOptionalRuntime: true,
            DetailsFr: "Anglais uniquement. Transcription locale sur CPU, sans GPU requis.\nPoids sous licence CC BY 4.0 : usage commercial autoris\u00e9 avec attribution \u00e0 Fermion Research et NVIDIA.",
            DetailsEn: "English only. Local CPU transcription; no GPU required.\nWeights use CC BY 4.0: commercial use is allowed with attribution to Fermion Research and NVIDIA.",
            PublisherKey: "fermion-research",
            PublisherDisplayName: "Fermion Research",
            ModelFamilyKey: "phonon",
            ModelFamilyDisplayName: "Phonon",
            VariantDisplayName: "2"),
        new(
            Key: "qwen3-asr-1.7b",
            DisplayName: "Qwen3-ASR-1.7B",
            RepoId: "Qwen/Qwen3-ASR-1.7B",
            SizeLabel: "4.7 GB",
            DownloadPatterns:
            [
                "config.json",
                "generation_config.json",
                "preprocessor_config.json",
                "processor_config.json",
                "tokenizer.json",
                "tokenizer_config.json",
                "special_tokens_map.json",
                "chat_template.json",
                "merges.txt",
                "vocab.json",
                "model.safetensors",
                "model-*.safetensors",
                "model.safetensors.index.json",
            ],
            RuntimeKind: ModelRuntimeKind.Qwen,
            SupportsFileTranscription: true,
            SupportsRealtimeTranscription: true,
            SupportsWindowsRuntime: true,
            SupportsLinuxRuntime: true,
            SupportsMacOsRuntime: true,
            RequiresOptionalRuntime: true,
            DetailsFr: "Aucun minimum officiel chiffr\u00e9 en RAM ou VRAM n'est publi\u00e9.\nUn GPU CUDA reste conseill\u00e9 pour de bonnes performances.",
            DetailsEn: "No official quantified RAM or VRAM minimum is published.\nA CUDA GPU is still recommended for good performance.",
            PublisherKey: "qwen",
            PublisherDisplayName: "Qwen",
            ModelFamilyKey: "qwen3-asr",
            ModelFamilyDisplayName: "Qwen3-ASR",
            VariantDisplayName: "1.7B"),
        new(
            Key: "qwen3-asr-0.6b",
            DisplayName: "Qwen3-ASR-0.6B",
            RepoId: "Qwen/Qwen3-ASR-0.6B",
            SizeLabel: "1.9 GB",
            DownloadPatterns:
            [
                "config.json",
                "generation_config.json",
                "preprocessor_config.json",
                "processor_config.json",
                "tokenizer.json",
                "tokenizer_config.json",
                "special_tokens_map.json",
                "chat_template.json",
                "merges.txt",
                "vocab.json",
                "model.safetensors",
            ],
            RuntimeKind: ModelRuntimeKind.Qwen,
            SupportsFileTranscription: true,
            SupportsRealtimeTranscription: true,
            SupportsWindowsRuntime: true,
            SupportsLinuxRuntime: true,
            SupportsMacOsRuntime: true,
            RequiresOptionalRuntime: true,
            DetailsFr: "Aucun minimum officiel chiffr\u00e9 en RAM ou VRAM n'est publi\u00e9.\nUn GPU CUDA reste conseill\u00e9 pour de bonnes performances.",
            DetailsEn: "No official quantified RAM or VRAM minimum is published.\nA CUDA GPU is still recommended for good performance.",
            PublisherKey: "qwen",
            PublisherDisplayName: "Qwen",
            ModelFamilyKey: "qwen3-asr",
            ModelFamilyDisplayName: "Qwen3-ASR",
            VariantDisplayName: "0.6B"),
        new(
            Key: "canary-1b-v2",
            DisplayName: "Canary-1B-v2",
            RepoId: "nvidia/canary-1b-v2",
            SizeLabel: "6.36 GB",
            DownloadPatterns:
            [
                "*.nemo",
                "*.json",
                "*.yaml",
                "*.yml",
                "*.txt",
            ],
            RuntimeKind: ModelRuntimeKind.Canary,
            SupportsFileTranscription: true,
            SupportsRealtimeTranscription: false,
            SupportsWindowsRuntime: false,
            SupportsLinuxRuntime: true,
            SupportsMacOsRuntime: false,
            RequiresOptionalRuntime: true,
            DetailsFr: "Support officiel orient\u00e9 Linux.\nAucun profil mat\u00e9riel Windows ou macOS n'est publi\u00e9 pour Voxcribe.",
            DetailsEn: "Official support is Linux-oriented.\nNo Windows or macOS hardware profile is published for Voxcribe.",
            PublisherKey: "nvidia",
            PublisherDisplayName: "NVIDIA",
            ModelFamilyKey: "canary",
            ModelFamilyDisplayName: "Canary",
            VariantDisplayName: null),
        new(
            Key: "parakeet-tdt-0.6b-v3",
            DisplayName: "Parakeet-TDT-0.6B-v3",
            RepoId: "nvidia/parakeet-tdt-0.6b-v3",
            SizeLabel: "2.51 GB",
            DownloadPatterns:
            [
                "*.nemo",
                "*.json",
                "*.yaml",
                "*.yml",
                "*.txt",
            ],
            RuntimeKind: ModelRuntimeKind.Parakeet,
            SupportsFileTranscription: true,
            SupportsRealtimeTranscription: false,
            SupportsWindowsRuntime: false,
            SupportsLinuxRuntime: true,
            SupportsMacOsRuntime: false,
            RequiresOptionalRuntime: true,
            DetailsFr: "Support officiel orient\u00e9 Linux.\nAucun profil mat\u00e9riel Windows ou macOS n'est publi\u00e9 pour Voxcribe.",
            DetailsEn: "Official support is Linux-oriented.\nNo Windows or macOS hardware profile is published for Voxcribe.",
            PublisherKey: "nvidia",
            PublisherDisplayName: "NVIDIA",
            ModelFamilyKey: "parakeet",
            ModelFamilyDisplayName: "Parakeet",
            VariantDisplayName: null),
        new(
            Key: "crisperwhisper-2-small",
            DisplayName: "CrisperWhisper 2.0 Small",
            RepoId: "nyralabs/CrisperWhisper2.0_small",
            SizeLabel: "489 MB",
            DownloadPatterns:
            [
                "LICENSE.md",
                "README.md",
                "config.json",
                "generation_config.json",
                "preprocessor_config.json",
                "tokenizer.json",
                "tokenizer_config.json",
                "special_tokens_map.json",
                "added_tokens.json",
                "normalizer.json",
                "merges.txt",
                "vocab.json",
                "model.safetensors",
                "model-*.safetensors",
                "model.safetensors.index.json",
            ],
            RuntimeKind: ModelRuntimeKind.CrisperWhisper,
            SupportsFileTranscription: true,
            SupportsRealtimeTranscription: false,
            SupportsWindowsRuntime: true,
            SupportsLinuxRuntime: true,
            SupportsMacOsRuntime: true,
            RequiresOptionalRuntime: true,
            DetailsFr: "Transcription verbatim : conserve les h\u00e9sitations, r\u00e9p\u00e9titions et faux d\u00e9parts.\nPoids r\u00e9serv\u00e9s \u00e0 la recherche et aux usages non commerciaux ; une licence Nyra est requise pour tout usage commercial.",
            DetailsEn: "Verbatim transcription preserves hesitations, repetitions, and false starts.\nWeights are limited to research and non-commercial use; a Nyra license is required for any commercial use.",
            PublisherKey: "nyra-labs",
            PublisherDisplayName: "Nyra Labs",
            ModelFamilyKey: "crisperwhisper-2",
            ModelFamilyDisplayName: "CrisperWhisper 2.0",
            VariantDisplayName: "Small"),
        new(
            Key: "crisperwhisper-2-medium",
            DisplayName: "CrisperWhisper 2.0 Medium",
            RepoId: "nyralabs/CrisperWhisper2.0_medium",
            SizeLabel: "1.54 GB",
            DownloadPatterns:
            [
                "LICENSE.md",
                "README.md",
                "config.json",
                "generation_config.json",
                "preprocessor_config.json",
                "tokenizer.json",
                "tokenizer_config.json",
                "special_tokens_map.json",
                "added_tokens.json",
                "normalizer.json",
                "merges.txt",
                "vocab.json",
                "model.safetensors",
                "model-*.safetensors",
                "model.safetensors.index.json",
            ],
            RuntimeKind: ModelRuntimeKind.CrisperWhisper,
            SupportsFileTranscription: true,
            SupportsRealtimeTranscription: false,
            SupportsWindowsRuntime: true,
            SupportsLinuxRuntime: true,
            SupportsMacOsRuntime: true,
            RequiresOptionalRuntime: true,
            DetailsFr: "Meilleur compromis taille/qualit\u00e9 recommand\u00e9 par Nyra. Transcription verbatim.\nPoids r\u00e9serv\u00e9s \u00e0 la recherche et aux usages non commerciaux ; une licence Nyra est requise pour tout usage commercial.",
            DetailsEn: "Nyra's recommended size/quality tradeoff. Verbatim transcription.\nWeights are limited to research and non-commercial use; a Nyra license is required for any commercial use.",
            PublisherKey: "nyra-labs",
            PublisherDisplayName: "Nyra Labs",
            ModelFamilyKey: "crisperwhisper-2",
            ModelFamilyDisplayName: "CrisperWhisper 2.0",
            VariantDisplayName: "Medium"),
        new(
            Key: "crisperwhisper-2-turbo",
            DisplayName: "CrisperWhisper 2.0 Turbo",
            RepoId: "nyralabs/CrisperWhisper2.0_turbo",
            SizeLabel: "1.63 GB",
            DownloadPatterns:
            [
                "LICENSE.md",
                "README.md",
                "config.json",
                "generation_config.json",
                "preprocessor_config.json",
                "tokenizer.json",
                "tokenizer_config.json",
                "special_tokens_map.json",
                "added_tokens.json",
                "normalizer.json",
                "merges.txt",
                "vocab.json",
                "model.safetensors",
                "model-*.safetensors",
                "model.safetensors.index.json",
            ],
            RuntimeKind: ModelRuntimeKind.CrisperWhisper,
            SupportsFileTranscription: true,
            SupportsRealtimeTranscription: false,
            SupportsWindowsRuntime: true,
            SupportsLinuxRuntime: true,
            SupportsMacOsRuntime: true,
            RequiresOptionalRuntime: true,
            DetailsFr: "Variante la plus rapide, avec une l\u00e9g\u00e8re baisse de qualit\u00e9. Transcription verbatim.\nPoids r\u00e9serv\u00e9s \u00e0 la recherche et aux usages non commerciaux ; une licence Nyra est requise pour tout usage commercial.",
            DetailsEn: "Fastest variant, with some quality degradation. Verbatim transcription.\nWeights are limited to research and non-commercial use; a Nyra license is required for any commercial use.",
            PublisherKey: "nyra-labs",
            PublisherDisplayName: "Nyra Labs",
            ModelFamilyKey: "crisperwhisper-2",
            ModelFamilyDisplayName: "CrisperWhisper 2.0",
            VariantDisplayName: "Turbo"),
        new(
            Key: "crisperwhisper-2-large",
            DisplayName: "CrisperWhisper 2.0 Large",
            RepoId: "nyralabs/CrisperWhisper2.0_large",
            SizeLabel: "3.10 GB",
            DownloadPatterns:
            [
                "LICENSE.md",
                "README.md",
                "config.json",
                "generation_config.json",
                "preprocessor_config.json",
                "tokenizer.json",
                "tokenizer_config.json",
                "special_tokens_map.json",
                "added_tokens.json",
                "normalizer.json",
                "merges.txt",
                "vocab.json",
                "model.safetensors",
                "model-*.safetensors",
                "model.safetensors.index.json",
            ],
            RuntimeKind: ModelRuntimeKind.CrisperWhisper,
            SupportsFileTranscription: true,
            SupportsRealtimeTranscription: false,
            SupportsWindowsRuntime: true,
            SupportsLinuxRuntime: true,
            SupportsMacOsRuntime: true,
            RequiresOptionalRuntime: true,
            DetailsFr: "Meilleure qualit\u00e9 parmi les variantes publiques. Transcription verbatim.\nPoids r\u00e9serv\u00e9s \u00e0 la recherche et aux usages non commerciaux ; une licence Nyra est requise pour tout usage commercial.",
            DetailsEn: "Best quality among the public variants. Verbatim transcription.\nWeights are limited to research and non-commercial use; a Nyra license is required for any commercial use.",
            PublisherKey: "nyra-labs",
            PublisherDisplayName: "Nyra Labs",
            ModelFamilyKey: "crisperwhisper-2",
            ModelFamilyDisplayName: "CrisperWhisper 2.0",
            VariantDisplayName: "Large"),
        new(
            Key: "whisper-large-v3",
            DisplayName: "Whisper large-v3",
            RepoId: "openai/whisper-large-v3",
            SizeLabel: "3.1 GB",
            DownloadPatterns:
            [
                "config.json",
                "generation_config.json",
                "preprocessor_config.json",
                "tokenizer.json",
                "tokenizer_config.json",
                "special_tokens_map.json",
                "added_tokens.json",
                "normalizer.json",
                "merges.txt",
                "vocab.json",
                "model.safetensors",
            ],
            RuntimeKind: ModelRuntimeKind.Whisper,
            SupportsFileTranscription: true,
            SupportsRealtimeTranscription: false,
            SupportsWindowsRuntime: true,
            SupportsLinuxRuntime: true,
            SupportsMacOsRuntime: true,
            RequiresOptionalRuntime: false,
            DetailsFr: "L'exemple officiel fonctionne sur CPU ou GPU CUDA.\nAucun minimum mat\u00e9riel chiffr\u00e9 n'est publi\u00e9 sur la carte.",
            DetailsEn: "The official example runs on CPU or a CUDA GPU.\nNo quantified hardware minimum is published on the card.",
            PublisherKey: "openai",
            PublisherDisplayName: "OpenAI",
            ModelFamilyKey: "whisper",
            ModelFamilyDisplayName: "Whisper",
            VariantDisplayName: null),
        new(
            Key: DefaultModelKey,
            DisplayName: "Voxtral Mini 3B",
            RepoId: "mistralai/Voxtral-Mini-3B-2507",
            SizeLabel: "9.35 GB",
            DownloadPatterns:
            [
                "config.json",
                "generation_config.json",
                "preprocessor_config.json",
                "params.json",
                "tekken.json",
                "model-*.safetensors",
                "model.safetensors.index.json",
            ],
            RuntimeKind: ModelRuntimeKind.Voxtral,
            SupportsFileTranscription: true,
            SupportsRealtimeTranscription: false,
            SupportsWindowsRuntime: true,
            SupportsLinuxRuntime: true,
            SupportsMacOsRuntime: true,
            RequiresOptionalRuntime: false,
            DetailsFr: "La carte indique environ 9.5 GB de RAM vid\u00e9o en BF16/FP16.",
            DetailsEn: "The card indicates about 9.5 GB of VRAM in BF16/FP16.",
            PublisherKey: "mistral",
            PublisherDisplayName: "Mistral",
            ModelFamilyKey: "voxtral-mini",
            ModelFamilyDisplayName: "Voxtral Mini",
            VariantDisplayName: "3B"),
        new(
            Key: "voxtral-small-24b",
            DisplayName: "Voxtral Small 24B",
            RepoId: "mistralai/Voxtral-Small-24B-2507",
            SizeLabel: "48.0 GB",
            DownloadPatterns:
            [
                "config.json",
                "generation_config.json",
                "preprocessor_config.json",
                "params.json",
                "tekken.json",
                "model-*.safetensors",
                "model.safetensors.index.json",
            ],
            RuntimeKind: ModelRuntimeKind.Voxtral,
            SupportsFileTranscription: true,
            SupportsRealtimeTranscription: false,
            SupportsWindowsRuntime: true,
            SupportsLinuxRuntime: true,
            SupportsMacOsRuntime: true,
            RequiresOptionalRuntime: false,
            DetailsFr: "La carte officielle recommande un service vLLM et indique environ 55 GB de VRAM GPU en bf16/fp16.",
            DetailsEn: "The official card recommends vLLM serving and indicates about 55 GB of GPU VRAM in bf16/fp16.",
            PublisherKey: "mistral",
            PublisherDisplayName: "Mistral",
            ModelFamilyKey: "voxtral-small",
            ModelFamilyDisplayName: "Voxtral Small",
            VariantDisplayName: null),
        new(
            Key: "voxtral-mini-4b-realtime",
            DisplayName: "Voxtral Mini 4B Realtime",
            RepoId: "mistralai/Voxtral-Mini-4B-Realtime-2602",
            SizeLabel: "17.7 GB",
            DownloadPatterns:
            [
                "config.json",
                "generation_config.json",
                "processor_config.json",
                "params.json",
                "tekken.json",
                "model.safetensors",
                "consolidated.safetensors",
                "model-*.safetensors",
                "model.safetensors.index.json",
            ],
            RuntimeKind: ModelRuntimeKind.Voxtral,
            SupportsFileTranscription: true,
            SupportsRealtimeTranscription: true,
            SupportsWindowsRuntime: true,
            SupportsLinuxRuntime: true,
            SupportsMacOsRuntime: true,
            RequiresOptionalRuntime: false,
            DetailsFr: "La carte indique >= 16 GB de m\u00e9moire GPU pour le service vLLM.",
            DetailsEn: "The card indicates >= 16 GB of GPU memory for vLLM serving.",
            PublisherKey: "mistral",
            PublisherDisplayName: "Mistral",
            ModelFamilyKey: "voxtral-mini",
            ModelFamilyDisplayName: "Voxtral Mini",
            VariantDisplayName: "4B Realtime"),
    ];

    public IReadOnlyList<TranscriptionModelDefinition> GetAll()
    {
        return Definitions;
    }

    public IReadOnlyList<TranscriptionModelDefinition> GetAvailableForCurrentOperatingSystem()
    {
        return Definitions
            .Where(definition => definition.SupportsCurrentOperatingSystem())
            .ToList();
    }

    public TranscriptionModelDefinition GetByKeyOrDefault(string? key)
    {
        return Definitions.FirstOrDefault(
                definition => string.Equals(definition.Key, key, StringComparison.OrdinalIgnoreCase))
            ?? GetDefaultForCurrentOperatingSystem();
    }

    public TranscriptionModelDefinition GetDefaultForCurrentOperatingSystem()
    {
        return Definitions.FirstOrDefault(definition =>
                   definition.Key == DefaultModelKey && definition.SupportsCurrentOperatingSystem())
               ?? Definitions.First(definition => definition.SupportsCurrentOperatingSystem());
    }
}
